[package]
name = "views"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gpui.workspace = true
i18n.workspace = true
icons.workspace = true
jiff.workspace = true
music.workspace = true
input.workspace = true
router.workspace = true
ui.workspace = true
state.workspace = true

[target.'cfg(windows)'.dependencies]
raw-window-handle.workspace = true
windows-sys.workspace = true
