[package]
name = "ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true
gpui.workspace = true
i18n.workspace = true
icons.workspace = true
image.workspace = true
log.workspace = true
serde.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
gpui_platform.workspace = true
