[package]
name = "music"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
bundled-sqlite = ["rusqlite/bundled", "storage/bundled-sqlite", "ytmusic/bundled-sqlite"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
blowfish.workspace = true
bytes.workspace = true
cbc.workspace = true
cipher.workspace = true
flate2.workspace = true
cpal.workspace = true
deunicode.workspace = true
dirs.workspace = true
http.workspace = true
librespot-core.workspace = true
librespot-oauth.workspace = true
librespot-playback.workspace = true
librespot-protocol.workspace = true
lofty.workspace = true
kakasi.workspace = true
log.workspace = true
md-5.workspace = true
percent-encoding.workspace = true
protobuf.workspace = true
reqwest.workspace = true
roxmltree.workspace = true
rodio = { workspace = true, features = ["symphonia-aac", "symphonia-alac", "symphonia-isomp4", "symphonia-libopus", "flac", "mp3", "vorbis", "wav"] }
rtrb.workspace = true
rusqlite.workspace = true
rustfft.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_norway.workspace = true
storage.workspace = true
tokio.workspace = true
ytmusic.workspace = true
