#!/usr/bin/env python3

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "THIRD-PARTY.md"

COPYRIGHT = re.compile(r"^\s*(?:#\s*)?Copyright\b.*$", re.MULTILINE)

PREAMBLE = """# Third-party licenses

Sonora is licensed under the GNU General Public License v3.0 or later; the full
text is in `COPYING`. GPUI pulls in `zlog`, `ztracing` and `ztracing_macro` from
the Zed repository, which carry the same license. The complete corresponding
source is the tagged commit of <https://github.com/sonorahq/sonora> together
with the dependency revisions pinned in `Cargo.lock`.

The binary embeds:

- Inter — SIL Open Font License 1.1, `assets/fonts/LICENSE.txt`
- Lucide icons — ISC License, `assets/icons/lucide/LICENSE`
- Iconoir — MIT License, `assets/icons/iconoir/LICENSE`
- Remix Icon 4.8.0 — Apache License 2.0, `assets/icons/remix/LICENSE`
- Solar Icon Set, Linear style — CC BY 4.0 by 480 Design, `assets/icons/solar/LICENSE`
- Simple Icons brand marks — CC0 1.0, `assets/icons/common/LICENSE`

Several dependencies are covered by the Mozilla Public License 2.0 — notably the
Symphonia decoders, `option-ext` and `priority-queue`. They are used unmodified;
their source is available from the upstream repositories linked below and from
<https://crates.io>.

Where a dependency offers a choice of licenses, Sonora relies on the permissive
option: Apache-2.0 for `self_cell`, MPL-2.0 for `priority-queue`.

Each section lists the crates covered by that license and the copyright notices
they carry, followed by one copy of the license text.

This file is generated by `scripts/generate-notices.py`; do not edit it by hand.
"""


def harvest():
    if not shutil.which("cargo-about"):
        sys.exit("notices: cargo-about missing, run `cargo install cargo-about`")

    done = subprocess.run(
        ["cargo", "about", "generate", "--format", "json"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if done.returncode != 0:
        sys.exit(done.stderr.strip() or "cannot run cargo about")
    return json.loads(done.stdout)


def notices(text):
    seen = []
    for line in COPYRIGHT.findall(text):
        line = " ".join(line.split()).rstrip(".")
        if line not in seen:
            seen.append(line)
    return seen


def link(crate):
    name = crate["name"]
    url = crate.get("repository") or f"https://crates.io/crates/{name}"
    return f"[{name} {crate['version']}]({url})"


def collect(report):
    groups = {}
    for entry in report["licenses"]:
        group = groups.setdefault(
            entry["id"], {"name": entry["name"], "text": None, "users": {}}
        )
        if group["text"] is None or entry.get("first_of_kind"):
            group["text"] = entry["text"]
        for use in entry["used_by"]:
            crate = use["crate"]
            key = f"{crate['name']} {crate['version']}"
            group["users"].setdefault(key, {"crate": crate, "notices": []})
            for notice in notices(entry["text"]):
                if notice not in group["users"][key]["notices"]:
                    group["users"][key]["notices"].append(notice)
    return groups


def render(report, groups):
    out = [PREAMBLE, "## Summary\n"]
    for row in report["overview"]:
        out.append(f"- {row['name']} — {row['count']} crate(s)")
    out.append("")

    for row in report["overview"]:
        group = groups[row["id"]]
        out.append(f"## {group['name']}\n")
        out.append(f"Used by {len(group['users'])} crate(s):\n")
        for key in sorted(group["users"], key=str.lower):
            user = group["users"][key]
            line = f"- {link(user['crate'])}"
            if user["notices"]:
                line += " — " + "; ".join(user["notices"])
            out.append(line)
        out.append("")
        body = dedent(group["text"]).strip("\n")
        out.append("```text")
        out.append(body)
        out.append("```\n")

    return "\n".join(out)


def dedent(text):
    lines = text.split("\n")
    pad = min(
        (len(line) - len(line.lstrip()) for line in lines if line.strip()),
        default=0,
    )
    return "\n".join(line[pad:] if line.strip() else "" for line in lines)


def main():
    report = harvest()
    groups = collect(report)
    OUTPUT.write_text(render(report, groups), encoding="utf-8")
    crates = sum(row["count"] for row in report["overview"])
    print(f"notices: {len(groups)} licenses, {crates} crates")


if __name__ == "__main__":
    main()
